### PR TITLE
Derequire

### PR DESCRIPTION
**Pull request by craigdallimore**
Hello

When trying `rdom` in [ramda repl](https://github.com/ramda/repl/pull/13#discussion_r80389677) I noticed that I was getting an error when `browserify` was evaluating the already browserified `dist/rdom.js`.

```
Error: Cannot find module './tags'
```

I suspect this is because of the presence of a `require` call [here](https://github.com/buzzdecafe/rdom/blob/master/dist/rdom.js#L30)

The issue can be recreated by running the following code in [requirebin](http://requirebin.com/)

```
var rdom = require('rdom');
var h1 = rdom.h1({}, ['hello']);
document.body.appendChild(h1);
```

The pull request adds a [derequire](https://www.npmjs.com/package/derequire) step into the building of this library, which is intended to modify the references to `require` so a downstream browserify will not attempt to re-require them.

Great library BTW! Very straightforward.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
"---FLAGRANT SYSTEM ERROR---"

well that's not very nice. Thanks for the fix

**Comment by buzzdecafe** [comment]
:dromedary_camel:

**Comment by buzzdecafe** [comment]
i'll release  a new package on npm tonight

**Comment by craigdallimore** [comment]
🐙

**Comment by buzzdecafe** [comment]
https://www.npmjs.com/package/rdom
0.6.0

**Pull request merged**
